[programs.localnet]
bdt_oracle = "4Xg8ntPZ8LE616Tqy4r18vBUuftombmb1jp15d6dqwAp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/generate_fixtures.js && npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"
bind_address = "127.0.0.1"

[[test.validator.account]]
address = "HQ2t2YrgoFB2sLq7GeyT5nzx5EMsc1DfWce1a42KHobc"
filename = "tests/fixtures/eur_usd_feed.json"
